driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12.7
    driver_config:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12.7.2
  - name: freebsd-10
    driver:
      ssh:
        shell: '"/bin/sh"'
  - name: freebsd-11
    driver:
      ssh:
        shell: '"/bin/sh"'
suites:
  - name: resource_test
    run_list:
      - recipe[test::default]
  - name: source_install
    run_list:
      - recipe[test::source]
