driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.9
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: freebsd-10.1
    driver:
      ssh:
        shell: '"/bin/sh"'

suites:
  - name: package_install
    run_list:
      - recipe[php::default]
  - name: source_install
    run_list:
      - recipe[php::default]
    attributes: { php: { install_method: "source" } }
  - name: fpm_test
    run_list:
      - recipe[php::default]
      - recipe[fpm_test]
    excludes:
      - centos-5.11
      - centos-6.7
      - fedora-22
      - fedora-23
      - freebsd-10.1
