driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
    run_list:
    - recipe[apt]
  - name: debian-8.1
    run_list:
      - recipe[apt]
  - name: fedora-21
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: freebsd-10.1
    driver:
      ssh:
        shell: '"/bin/sh"'

suites:
  - name: default
    run_list:
      - recipe[php::default]
  - name: fpm_test
    run_list:
      - recipe[php::default]
      - recipe[fpm_test]
    excludes:
      - centos-5.11
      - centos-6.7
      - fedora-21
      - freebsd-10.1
