AllCops:
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
